### ISSUE TITLE
Add different point images as well as colors to avoid confusion.

### ISSUE THREAD

**Issue by mace1099** [MTUHIDE/ArcelorMittal#4]

**Comment by abigmyers** [comment]
There were no options for other point images, so I changed the color of the inner circle of each marker instead. Since the outer marker color is determined by the employee name, I set the inner color to be determined by customer location. That way, right now, each marker on the map has a unique color combination.

Once we have a more complete data set, I'd like to have the inner color determined by a combination of the customer's name and location, but currently, "Customer A" and "Customer B" are too similar.
